version: '2'
services:
  uniqueidmysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pacifica_uniqueid
      MYSQL_USER: uniqueid
      MYSQL_PASSWORD: uniqueid
    ports:
     - 3306:3306

  uniqueid:
    build: .
    links:
      - uniqueidmysql:mysql
    ports:
      - 8051:8051
    environment:
      PEEWEE_ADDR: mysql
